[package]
name = "gravity"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0-rc.5"

[dev-dependencies]
macroquad = "0.4.14"
flat_space_examples = {path="../../../flat_space_examples"}
view = {path = "../../../view"}